/* Per-distro live-boot profiles + GRUB menu generation. This is the one place
 * the fiddly "how does THIS family boot live off a squashfs" logic lives
 * (mirrors ISO2Drive's profile.c + grubcfg.c). */
#include "drive2iso/bootcfg.h"
#include "drive2iso/util.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/* v1: debian/ubuntu/generic (live-boot, /live/filesystem.squashfs) are fully
 * wired. fedora (dracut dmsquash-live) and arch (mkinitcpio archiso) rows use
 * their native layouts and need their own initrd tooling to be end-to-end. */
static const live_profile_t profiles[] = {
    { "ubuntu",  "live-boot",  "boot=live components quiet splash",         "live/filesystem.squashfs" },
    { "mint",    "live-boot",  "boot=live components quiet splash",         "live/filesystem.squashfs" },
    { "debian",  "live-boot",  "boot=live components quiet splash",         "live/filesystem.squashfs" },
    { "fedora",  "dracut",     "root=live:CDLABEL=%s rd.live.image quiet",  "LiveOS/squashfs.img" },
    { "rhel",    "dracut",     "root=live:CDLABEL=%s rd.live.image quiet",  "LiveOS/squashfs.img" },
    { "arch",    "mkinitcpio", "archisobasedir=arch archisolabel=%s",       "arch/x86_64/airootfs.sfs" },
    { "manjaro", "mkinitcpio", "archisobasedir=manjaro archisolabel=%s",    "manjaro/x86_64/rootfs.sfs" },
};
static const live_profile_t generic_profile =
    { "generic", "live-boot", "boot=live components", "live/filesystem.squashfs" };

const live_profile_t *bootcfg_generic(void) { return &generic_profile; }

const live_profile_t *bootcfg_profile(const char *distro) {
    if (!distro || !*distro) return NULL;
    char low[64];
    size_t i = 0;
    for (; distro[i] && i < sizeof low - 1; ++i)
        low[i] = (char)tolower((unsigned char)distro[i]);
    low[i] = '\0';
    for (size_t j = 0; j < sizeof profiles / sizeof profiles[0]; ++j)
        if (strstr(low, profiles[j].family)) return &profiles[j];
    return NULL;
}

/* Replace the first "%s" in `tmpl` with `label` (manual, so a stray '%' in the
 * table can never reach printf). Heap-allocated; caller frees. */
static char *subst_label(const char *tmpl, const char *label) {
    const char *pct = strstr(tmpl, "%s");
    if (!pct) return xstrdup(tmpl);
    size_t head = (size_t)(pct - tmpl);
    char *out = malloc(head + strlen(label) + strlen(pct + 2) + 1);
    if (!out) return NULL;
    memcpy(out, tmpl, head);
    strcpy(out + head, label);
    strcat(out + head, pct + 2);
    return out;
}

int bootcfg_write_linux(const char *stage_dir, const char *label,
                        const char *kernel, const char *initrd,
                        const live_profile_t *prof, bool commit) {
    if (!prof) prof = &generic_profile;
    char *cmd = subst_label(prof->cmdline, label ? label : "DRIVE2ISO");
    if (!cmd) return -1;

    char *cfg = str_format(
        "# generated by Drive2Iso — family=%s live-layer=%s\n"
        "set default=0\n"
        "set timeout=10\n"
        "insmod all_video\n"
        "\n"
        "menuentry \"Drive2Iso live — %s\" {\n"
        "    linux /live/%s %s\n"
        "    initrd /live/%s\n"
        "}\n"
        "menuentry \"Drive2Iso live — %s (safe graphics)\" {\n"
        "    linux /live/%s %s nomodeset\n"
        "    initrd /live/%s\n"
        "}\n",
        prof->family, prof->live_layer,
        label ? label : "DRIVE2ISO", kernel, cmd, initrd,
        label ? label : "DRIVE2ISO", kernel, cmd, initrd);
    free(cmd);
    if (!cfg) return -1;

    char *path = str_format("%s/boot/grub/grub.cfg", stage_dir);
    int rc = -1;
    if (path) {
        if (!commit) {
            log_info("(dry-run) write %s :", path);
            fputs(cfg, stdout);
            rc = 0;
        } else {
            rc = write_file(path, cfg);
            if (rc == 0) log_info("wrote %s (squashfs -> /%s)", path, prof->squash_rel);
        }
    }
    free(cfg); free(path);
    return rc;
}
